### ISSUE TITLE
Repository description declares v2 to be experimental

### ISSUE THREAD

**Issue by surfsoft** [Pi4J/pi4j-v2#247]
Really trivial but the repo description declares v2 to be experimental and as such I'd not paid it any attention (shocking, I know, a dev who doesn't read the docs). I think you'd do yourselves a favour by updating the repo description!

**Comment by eitch** [comment]
Thanks, just changed it! =))

**Comment by FDelporte** [comment]
thanks @surfsoft for noticing! seems we just missed this ourselves, yeah who reads docs anyway (message brought to you by the docs writer) :-)
